name: bsteeleMusicLib
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  logger: ">=0.8.2"
  quiver: "2.0.5"
  http: ^0.12.0+4
  archive: ^2.0.11

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
