name: bsteeleMusicLib
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  logger: ^0.8.3
  quiver: ^2.1.3
  http: ^0.12.0+4
  archive: ^2.0.13
  universal_html: ^1.1.18

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.2
  test_api: ^0.2.15
