/// Words that elude syllable-counting rules.
Map<String, int> problematic = {
  'abalone': 4,
  'abare': 3,
  'abed': 2,
  'abruzzese': 4,
  'abbruzzese': 4,
  'aborigine': 5,
  'acreage': 3,
  'adame': 3,
  'adieu': 2,
  'adobe': 3,
  'anemone': 4,
  'apache': 3,
  'aphrodite': 4,
  'apostrophe': 4,
  'ariadne': 4,
  'cafe': 2,
  'calliope': 4,
  'catastrophe': 4,
  'chile': 2,
  'chloe': 2,
  'circe': 2,
  'coyote': 3,
  'conscious': 2,
  'cruel': 2,
  'epitome': 4,
  'forever': 3,
  'gethsemane': 4,
  'guacamole': 4,
  'hyperbole': 4,
  'jesse': 2,
  'jukebox': 2,
  'karate': 3,
  'machete': 3,
  'maybe': 2,
  'people': 2,
  'poet': 2,
  'recipe': 3,
  'sesame': 3,
  'shoreline': 2,
  'simile': 3,
  'syncope': 3,
  'tamale': 3,
  'yosemite': 4,
  'daphne': 2,
  'eurydice': 4,
  'euterpe': 3,
  'hermione': 4,
  'penelope': 4,
  'persephone': 4,
  'phoebe': 2,
  'precious': 2,
  'zoe': 2
};

Map<String, List<String>> problematicSyllables = {
  'abalone': ['ab', 'a', 'lo', 'ne'],
  'abare': ['a', 'bar', 'e'],
  'abed': ['a', 'bed'],
  'abruzzese': ['a', 'bruz', 'ze', 'se'],
  'abbruzzese': ['ab', 'bruz', 'ze', 'se'], //  a guess
  'aborigine': ['ab', 'o', 'rig', 'i', 'ne'],
  'acreage': ['a', 'cre', 'age'],
  'adame': ['a', 'dame'], //  a guess
  'adieu': ['a', 'dieu'],
  'adobe': ['a', 'do', 'be'],
  'anemone': ['a', 'nem', 'o', 'ne'],
  'apache': ['a', 'pach', 'e'],
  'aphrodite': ['aph', 'ro', 'di', 'te'],
  'apostrophe': ['a', 'pos', 'tro', 'phe'],
  'ariadne': ['ar', 'i', 'ad', 'ne'],
  'cafe': ['ca', 'fe'],
  'calliope': ['cal', 'li', 'o', 'pe'],
  'catastrophe': ['ca', 'tas', 'tro', 'phe'],
  'chile': ['chil', 'e'],
  'chloe': ['chlo', 'e'],
  'circe': ['cir', 'ce'],
  'coyote': ['coy', 'o', 'te'],
  'conscious': ['con', 'scious'],
  'cruel': ['cru', 'el'],
  'epitome': ['e', 'pit', 'o', 'me'],
  'forever': ['for', 'ev', 'er'],
  'gethsemane': ['geth', 'sem', 'a', 'ne'],
  'guacamole': ['gua', 'ca', 'mo', 'le'],
  'hyperbole': ['hy', 'per', 'bo', 'le'],
  'jesse': ['jes', 'se'],
  'jukebox': ['juke', 'box'],
  'karate': ['ka', 'ra', 'te'],
  'machete': ['ma', 'che', 'te'],
  'maybe': ['may', 'be'],
  'people': ['peo', 'ple'],
  'poet': ['po', 'et'],
  'recipe': ['rec', 'i', 'pe'],
  'sesame': ['ses', 'a', 'me'],
  'shoreline': ['shore', 'line'],
  'simile': ['sim', 'i', 'le'],
  'syncope': ['syn', 'co', 'pe'],
  'tamale': ['ta', 'ma', 'le'],
  'yosemite': ['yo', 'se', 'mi', 'te'],
  'daphne': ['daph', 'ne'],
  'eurydice': ['eu', 'ryd', 'i', 'ce'],
  'euterpe': ['eu', 'ter', 'pe'],
  'hermione': ['hermione'],
  'penelope': ['pe', 'nel', 'o', 'pe'],
  'persephone': ['per', 'seph', 'o', 'ne'],
  'phoebe': ['phoe', 'be'],
  'precious': ['pre', 'cious'],
  'zoe': ['zo', 'e'],
};
